---
title: "biostatistics_week11"
author: "Kevin Jou"
date: "2023-12-27"
output: html_document
---

```{r}
player_stats <- read.csv("ppg2008.csv", row.names = 1)
```

```{r}
# Selecting attributes for clustering
clustering_data <- player_stats[, c("PTS", "AST", "TRB", "TO", "TRB")]


# Choosing the number of clusters (e.g., 3 clusters)
k <- 3

# Performing k-means clustering
kmeans_result <- kmeans(player_stats, centers = k)

# Adding cluster labels to the original dataset
player_stats$KMeans_Cluster <- as.factor(kmeans_result$cluster)

table(player_stats$KMeans_Cluster)
```

```{r}
# Calculating distances
distances <- dist(scale(clustering_data))

# Performing hierarchical clustering (using complete linkage)
hclust_result <- hclust(distances, method = "complete")

# Choosing the number of clusters
k <- 4

# Cutting the dendrogram to obtain clusters
clusters <- cutree(hclust_result, k)

# Adding cluster labels to the original dataset
player_stats$Hierarchical_Cluster <- as.factor(clusters)

# Displaying the clusters
table(player_stats$Hierarchical_Cluster)

# Performing hierarchical clustering (using complete linkage)
hclust_result <- hclust(distances, method = "complete")

# Visualizing the resulting dendrogram (tree)
plot(hclust_result, main = "Dendrogram of Hierarchical Clustering")

```




