---
title: "computational_biology_assignment_2_gillespies"
author: "Kevin Jou"
date: "2024-03-05"
output: html_document
---

```{r}
# Load required library
library(deSolve)
library(ggplot2)

# Define the function for the ODE system
water_dissociation <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    # Calculate forward and reverse rate constants
    forward_rate <- Ka * H2O
    reverse_rate <- Ka * H * OH
    
    # ODEs
    dH2O <- -forward_rate + reverse_rate
    dH <- forward_rate - reverse_rate
    dOH <- forward_rate - reverse_rate
    
    return(list(c(dH2O, dH, dOH)))
  })
}

# Parameters
parameters <- list(Ka = 10^(-14),  # Equilibrium constant for water dissociation
                    H2O_0 = 250,   # Initial number of water molecules
                    H_0 = 250,        # Initial number of H+ ions
                    OH_0 = 250)       # Initial number of OH- ions

# Initial conditions
initial_state <- c(H2O = parameters$H2O_0,
                   H = parameters$H_0,
                   OH = parameters$OH_0)


# Time points for simulation
times <- seq(0, 100, by = 0.1)

# Solve the ODE system
out <- ode(y = initial_state, times = times, func = water_dissociation, parms = parameters)

# Plot results
ggplot(data = as.data.frame(out), aes(x = time)) +
  geom_line(aes(y = H2O, color = "Water")) +
  geom_line(aes(y = H, color = "H+")) +
  geom_line(aes(y = OH, color = "OH-")) +
  labs(x = "Time", y = "Number of Molecules", title = "Water Dissociation Simulation") +
  scale_color_manual(values = c("Water" = "blue", "H+" = "red", "OH-" = "green")) +
  theme_minimal()
```
```{r}
# Define the function for the ODE system
water_dissociation <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    # Calculate forward and reverse rate constants
    forward_rate <- Ka * H2O
    reverse_rate <- Ka * H * OH
    
    # ODEs
    dH2O <- -forward_rate + reverse_rate
    dH <- forward_rate - reverse_rate
    dOH <- forward_rate - reverse_rate
    
    return(list(c(dH2O, dH, dOH)))
  })
}

# Parameters
parameters <- list(Ka = 10^(-14))

# Generate random initial concentrations
initial_concentrations <- runif(3, min = 0, max = 1000)  # Random values between 0 and 1000

# Initial conditions
initial_state <- c(H2O = initial_concentrations[1],
                   H = initial_concentrations[2],
                   OH = initial_concentrations[3])


# Time points for simulation
times <- seq(0, 100, by = 0.1)

# Solve the ODE system
out <- ode(y = initial_state, times = times, func = water_dissociation, parms = parameters)

# Plot results
ggplot(data = as.data.frame(out), aes(x = time)) +
  geom_line(aes(y = H2O, color = "Water")) +
  geom_line(aes(y = H, color = "H+")) +
  geom_line(aes(y = OH, color = "OH-")) +
  labs(x = "Time", y = "Number of Molecules", title = "Water Dissociation Simulation") +
  scale_color_manual(values = c("Water" = "blue", "H+" = "red", "OH-" = "green")) +
  theme_minimal()
```
```{r}
# Define the function for the ODE system
water_dissociation <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    # Calculate forward and reverse rate constants
    forward_rate <- Ka * H2O
    reverse_rate <- Ka * H * OH
    
    # ODEs
    dH2O <- -forward_rate + reverse_rate
    dH <- forward_rate - reverse_rate
    dOH <- forward_rate - reverse_rate
    
    return(list(c(dH2O, dH, dOH)))
  })
}

# Parameters
parameters <- list(Ka = 10^(-14))

# Generate random initial concentrations
initial_concentrations <- runif(3, min = 0, max = 1000)  # Random values between 0 and 1000

# Initial conditions
initial_state <- c(H2O = initial_concentrations[1],
                   H = initial_concentrations[2],
                   OH = initial_concentrations[3])


# Time points for simulation
times <- seq(0, 100, by = 0.1)

# Solve the ODE system
out <- ode(y = initial_state, times = times, func = water_dissociation, parms = parameters)

# Plot results
ggplot(data = as.data.frame(out), aes(x = time)) +
  geom_line(aes(y = H2O, color = "Water")) +
  geom_line(aes(y = H, color = "H+")) +
  geom_line(aes(y = OH, color = "OH-")) +
  labs(x = "Time", y = "Number of Molecules", title = "Water Dissociation Simulation") +
  scale_color_manual(values = c("Water" = "blue", "H+" = "red", "OH-" = "green")) +
  theme_minimal()
```


```{r}
# Define the function for the ODE system
water_dissociation <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    # Calculate forward and reverse rate constants
    forward_rate <- Ka * H2O
    reverse_rate <- Ka * H * OH
    
    # ODEs
    dH2O <- -forward_rate + reverse_rate
    dH <- forward_rate - reverse_rate
    dOH <- forward_rate - reverse_rate
    
    return(list(c(dH2O, dH, dOH)))
  })
}

# Parameters
parameters <- list(Ka = 10^(-14))

# Generate random initial concentrations
initial_concentrations <- runif(3, min = 0, max = 1000)  # Random values between 0 and 1000

# Initial conditions
initial_state <- c(H2O = initial_concentrations[1],
                   H = initial_concentrations[2],
                   OH = initial_concentrations[3])


# Time points for simulation
times <- seq(0, 100, by = 0.1)

# Solve the ODE system
out <- ode(y = initial_state, times = times, func = water_dissociation, parms = parameters)

# Plot results
ggplot(data = as.data.frame(out), aes(x = time)) +
  geom_line(aes(y = H2O, color = "Water")) +
  geom_line(aes(y = H, color = "H+")) +
  geom_line(aes(y = OH, color = "OH-")) +
  labs(x = "Time", y = "Number of Molecules", title = "Water Dissociation Simulation") +
  scale_color_manual(values = c("Water" = "blue", "H+" = "red", "OH-" = "green")) +
  theme_minimal()
```
